### ISSUE TITLE
为什么是出现两串代码

### ISSUE THREAD

**Issue by Sakira6666** [esozh/eso_zh_server#1]
![11](https://cloud.githubusercontent.com/assets/12528300/12111506/d291cfc4-b3d0-11e5-9b5a-25bfc04c42eb.png)

**Comment by bssthu** [comment]
是偶尔这样吗？好像有时候会识别错。。

**Comment by bssthu** [comment]
也可能是因为我太久没更新了。。 新版本Addon下载地址：https://github.com/esozh/eso_zh/releases/latest

如果安装正常的话，在游戏里和NPC对话时会出现一个二维码
![qr](https://cloud.githubusercontent.com/assets/7445439/12219690/8a2b3a2e-b789-11e5-8183-17d5b08f4b46.png)

**Comment by Sakira6666** [comment]
好吧 我插件没安装好
